baseURL = 'https://k3t.tech/'
languageCode = 'en-us'
title = 'highly kotted site :3'
theme        = "hello-4s3ti"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "the disaster of some k3t."
  keywords = "homepage"
  backgroundImage = "the-matrix-has-you.gif"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "highly kotted site"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "k3t.tech"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"  
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"